 # List of big joints (according to DAS66)
L_Big_Joints_66 = [
    'Pijn_schouder L_positive', 
    'Pijn_schouder R_positive', 
    'Pijn_Elleboog L_positive',
    'Pijn_elleboog R_positive', 
    'Pijn_heup links_positive', 
    'Pijn_heup rechts_positive', 
    'Pijn_knie links_positive', 
    'Pijn_knie rechts_positive',
    'Zwelling_schouder L_positive', 
    'Zwelling_schouder R_positive', 
    'Zwelling_Elleboog L_positive', 
    'Zwelling_elleboog R_positive',
    'Zwelling_heup links_positive', 
    'Zwelling_heup rechts_positive',
    'Zwelling_knie links_positive', 
    'Zwelling_knie rechts_positive',
    'Pijn_onderste spronggewricht links_positive', 
    'Pijn_onderste spronggewricht rechts_positive', 
    'Pijn_bovenste spronggewicht links_positive', 
    'Pijn_bovenste spronggewricht rechts_positive',
    'Zwelling_onderste spronggewricht links_positive', 
    'Zwelling_onderste spronggewricht rechts_positive', 
    'Zwelling_bovenste spronggewicht links_positive', 
    'Zwelling_bovenste spronggewricht rechts_positive',
    'Zwelling_cervical spine_positive', 
    'Pijn_cervical spine_positive', 
    'Pijn_sacro-ileacaal gewricht links_positive', 
    'Pijn_sacro-ileacaal gewricht rechts_positive'
]# Sacro-ileacaal has no 'Zwelling' version

 # List of tender foot joints (according to DAS66) - now also including PIP & MTP1
L_Foot_Tender_66 = ['Pijn_mtp 1 links_positive',
 'Pijn_mtp 1 rechts_positive',
 'Pijn_mtp 2 links_positive',
 'Pijn_mtp 2 rechts_positive',
 'Pijn_mtp 3 links_positive',
 'Pijn_mtp 3 rechts_positive',
 'Pijn_mtp 4 links_positive',
 'Pijn_mtp 4 rechts_positive',
 'Pijn_mtp 5 links_positive',
 'Pijn_mtp 5 rechts_positive',
 'Pijn_onderste spronggewricht rechts_positive', 'Pijn_bovenste spronggewicht links_positive', 'Pijn_bovenste spronggewricht rechts_positive',
  # also PIP  in feet (part of DAS66)
 'Pijn_pip 2 links voet_positive',
 'Pijn_pip 2 rechts voet_positive',
 'Pijn_pip 3 links voet_positive',
 'Pijn_pip 3 rechts voet_positive',
 'Pijn_pip 4 links voet_positive',
 'Pijn_pip 4 rechts voet_positive',
 'Pijn_pip 5 links voet_positive',
 'Pijn_pip 5 rechts voet_positive',
 
 # also MTP 1
 'Pijn_mtp 1 links_positive',
 'Pijn_mtp 1 rechts_positive',
           ]

 # List of swollen foot joints (according to DAS66) - now also including PIP & MTP1
L_Foot_Swelling_66 = [
    'Zwelling_onderste spronggewricht links_positive',
    'Zwelling_onderste spronggewricht rechts_positive',
    'Zwelling_bovenste spronggewicht links_positive',
    'Zwelling_bovenste spronggewricht rechts_positive',
    'Zwelling_mtp 2 links_positive',
    'Zwelling_mtp 2 rechts_positive',
    'Zwelling_mtp 3 links_positive',
    'Zwelling_mtp 3 rechts_positive',
    'Zwelling_mtp 4 links_positive',
    'Zwelling_mtp 4 rechts_positive',
    'Zwelling_mtp 5 links_positive',
    'Zwelling_mtp 5 rechts_positive',
    
    ## pip in feet part of DAS66
    'Zwelling_pip 2 links voet_positive',
    'Zwelling_pip 2 rechts voet_positive',
    'Zwelling_pip 3 links voet_positive',
    'Zwelling_pip 3 rechts voet_positive',
    'Zwelling_pip 4 links voet_positive',
    'Zwelling_pip 4 rechts voet_positive',
    'Zwelling_pip 5 links voet_positive',
    'Zwelling_pip 5 rechts voet_positive',
    
    ## mtp 1 in feet part of DAS66
    'Zwelling_mtp 1 links_positive',
    'Zwelling_mtp 1 rechts_positive',
    ## 
]

 # List of tender hand joints (according to DAS66) - now also including DIP
L_Hand_Tender_66 = [
    'Pijn_pip 2 links hand_positive', 'Pijn_pip 2 rechts hand_positive',
    'Pijn_pip 3 links hand_positive', 'Pijn_pip 3 rechts hand_positive',
    'Pijn_pip 4 links hand_positive', 'Pijn_pip 4 rechts hand_positive',
    'Pijn_pip 5 links hand_positive', 'Pijn_pip 5 rechts hand_positive',
    'Pijn_mcp 1 links_positive', 'Pijn_mcp 1 rechts_positive',
    'Pijn_mcp 2 links_positive', 'Pijn_mcp 2 rechts_positive',
    'Pijn_mcp 3 links_positive', 'Pijn_mcp 3 rechts_positive',
    'Pijn_mcp 4 links_positive', 'Pijn_mcp 4 rechts_positive',
    'Pijn_mcp 5 links_positive', 'Pijn_mcp 5 rechts_positive',
    'Pijn_IP links_positive', 'Pijn_IP rechts_positive',
    'Pijn_dip 2 links_positive',
     'Pijn_dip 2 rechts_positive',
     'Pijn_dip 3 links_positive',
     'Pijn_dip 3 rechts_positive',
     'Pijn_dip 4 links_positive',
     'Pijn_dip 4 rechts_positive',
     'Pijn_dip 5 links_positive',
     'Pijn_dip 5 rechts_positive',
]

 # List of swollen hand joints (according to DAS66) - now also including DIP
L_Hand_Swelling_66 = [
    'Zwelling_pols L_positive', 'Zwelling_pols R_positive',
    'Zwelling_pip 2 links hand_positive', 'Zwelling_pip 2 rechts hand_positive',
    'Zwelling_pip 3 links hand_positive', 'Zwelling_pip 3 rechts hand_positive',
    'Zwelling_pip 4 links hand_positive', 'Zwelling_pip 4 rechts hand_positive',
    'Zwelling_pip 5 links hand_positive', 'Zwelling_pip 5 rechts hand_positive',
    'Zwelling_mcp 1 links_positive', 'Zwelling_mcp 1 rechts_positive',
    'Zwelling_mcp 2 links_positive', 'Zwelling_mcp 2 rechts_positive',
    'Zwelling_mcp 3 links_positive', 'Zwelling_mcp 3 rechts_positive',
    'Zwelling_mcp 4 links_positive', 'Zwelling_mcp 4 rechts_positive',
    'Zwelling_mcp 5 links_positive', 'Zwelling_mcp 5 rechts_positive',
    'Zwelling_IP links_positive', 'Zwelling_IP rechts_positive',
    'Zwelling_dip 2 links_positive',
     'Zwelling_dip 2 rechts_positive',
     'Zwelling_dip 3 links_positive',
     'Zwelling_dip 3 rechts_positive',
     'Zwelling_dip 4 links_positive',
     'Zwelling_dip 4 rechts_positive',
     'Zwelling_dip 5 links_positive',
     'Zwelling_dip 5 rechts_positive',
     
]



 # List of small joints (according to DAS66) - now also including DIP from hand, PIP & MTP1 from feet
L_Small_Joints_66 = ['Pijn_mtp 1 links_positive',
 'Pijn_mtp 1 rechts_positive',
 'Pijn_mtp 2 links_positive',
 'Pijn_mtp 2 rechts_positive',
 'Pijn_mtp 3 links_positive',
 'Pijn_mtp 3 rechts_positive',
 'Pijn_mtp 4 links_positive',
 'Pijn_mtp 4 rechts_positive',
 'Pijn_mtp 5 links_positive',
 'Pijn_mtp 5 rechts_positive',
 'Pijn_pip 2 links voet_positive',
 'Pijn_pip 2 rechts voet_positive',
 'Pijn_pip 3 links voet_positive',
 'Pijn_pip 3 rechts voet_positive',
 'Pijn_pip 4 links voet_positive',
 'Pijn_pip 4 rechts voet_positive',
 'Pijn_pip 5 links voet_positive',
 'Pijn_pip 5 rechts voet_positive',
    'Pijn_pip 2 links hand_positive', 'Pijn_pip 2 rechts hand_positive',
    'Pijn_pip 3 links hand_positive', 'Pijn_pip 3 rechts hand_positive',
    'Pijn_pip 4 links hand_positive', 'Pijn_pip 4 rechts hand_positive',
    'Pijn_pip 5 links hand_positive', 'Pijn_pip 5 rechts hand_positive',
    'Pijn_mcp 1 links_positive', 'Pijn_mcp 1 rechts_positive',
    'Pijn_mcp 2 links_positive', 'Pijn_mcp 2 rechts_positive',
    'Pijn_mcp 3 links_positive', 'Pijn_mcp 3 rechts_positive',
    'Pijn_mcp 4 links_positive', 'Pijn_mcp 4 rechts_positive',
    'Pijn_mcp 5 links_positive', 'Pijn_mcp 5 rechts_positive',
    'Pijn_IP links_positive', 'Pijn_IP rechts_positive',
    'Zwelling_pols L_positive', 'Zwelling_pols R_positive',
    'Zwelling_pip 2 links hand_positive', 'Zwelling_pip 2 rechts hand_positive',
    'Zwelling_pip 3 links hand_positive', 'Zwelling_pip 3 rechts hand_positive',
    'Zwelling_pip 4 links hand_positive', 'Zwelling_pip 4 rechts hand_positive',
    'Zwelling_pip 5 links hand_positive', 'Zwelling_pip 5 rechts hand_positive',
    'Zwelling_mcp 1 links_positive', 'Zwelling_mcp 1 rechts_positive',
    'Zwelling_mcp 2 links_positive', 'Zwelling_mcp 2 rechts_positive',
    'Zwelling_mcp 3 links_positive', 'Zwelling_mcp 3 rechts_positive',
    'Zwelling_mcp 4 links_positive', 'Zwelling_mcp 4 rechts_positive',
    'Zwelling_mcp 5 links_positive', 'Zwelling_mcp 5 rechts_positive',
    'Zwelling_IP links_positive', 'Zwelling_IP rechts_positive',
    'Zwelling_mtp 2 links_positive',
    'Zwelling_mtp 2 rechts_positive',
    'Zwelling_mtp 3 links_positive',
    'Zwelling_mtp 3 rechts_positive',
    'Zwelling_mtp 4 links_positive',
    'Zwelling_mtp 4 rechts_positive',
    'Zwelling_mtp 5 links_positive',
    'Zwelling_mtp 5 rechts_positive',
    'Zwelling_sternoclaviculair L_positive', 'Zwelling_sternoclaviculair R_positive',
    'Pijn_sternoclaviculair L_positive', 'Pijn_sternoclaviculair R_positive',
    'Zwelling_acromioclaviaculair L_positive', 'Zwelling_acromioclaviaculair R_positive',
    'Pijn_acromioclaviaculair L_positive', 'Pijn_acromioclaviaculair R_positive',
    'Pijn_dip 2 links_positive',
     'Pijn_dip 2 rechts_positive',
     'Pijn_dip 3 links_positive',
     'Pijn_dip 3 rechts_positive',
     'Pijn_dip 4 links_positive',
     'Pijn_dip 4 rechts_positive',
     'Pijn_dip 5 links_positive',
     'Pijn_dip 5 rechts_positive',
     'Pijn_mtp 1 links_positive',
     'Pijn_mtp 1 rechts_positive',
     'Zwelling_dip 2 links_positive',
     'Zwelling_dip 2 rechts_positive',
     'Zwelling_dip 3 links_positive',
     'Zwelling_dip 3 rechts_positive',
     'Zwelling_dip 4 links_positive',
     'Zwelling_dip 4 rechts_positive',
     'Zwelling_dip 5 links_positive',
     'Zwelling_dip 5 rechts_positive',
     'Zwelling_mtp 1 links_positive',
     'Zwelling_mtp 1 rechts_positive',
     'Zwelling_pip 2 links voet_positive',
    'Zwelling_pip 2 rechts voet_positive',
    'Zwelling_pip 3 links voet_positive',
    'Zwelling_pip 3 rechts voet_positive',
    'Zwelling_pip 4 links voet_positive',
    'Zwelling_pip 4 rechts voet_positive',
    'Zwelling_pip 5 links voet_positive',
    'Zwelling_pip 5 rechts voet_positive',
]

L_DAS_Joints_28 = [
    'Pijn_pols L_positive', 'Pijn_pols R_positive',
    'Pijn_pip 2 links hand_positive', 'Pijn_pip 2 rechts hand_positive',
    'Pijn_pip 3 links hand_positive', 'Pijn_pip 3 rechts hand_positive',
    'Pijn_pip 4 links hand_positive', 'Pijn_pip 4 rechts hand_positive',
    'Pijn_pip 5 links hand_positive', 'Pijn_pip 5 rechts hand_positive',
    'Pijn_mcp 1 links_positive', 'Pijn_mcp 1 rechts_positive',
    'Pijn_mcp 2 links_positive', 'Pijn_mcp 2 rechts_positive',
    'Pijn_mcp 3 links_positive', 'Pijn_mcp 3 rechts_positive',
    'Pijn_mcp 4 links_positive', 'Pijn_mcp 4 rechts_positive',
    'Pijn_mcp 5 links_positive', 'Pijn_mcp 5 rechts_positive',
    'Pijn_IP links_positive', 'Pijn_IP rechts_positive',
    'Pijn_schouder L_positive', 'Pijn_schouder R_positive',
    'Pijn_Elleboog L_positive', 'Pijn_elleboog R_positive',
    'Pijn_knie links_positive', 'Pijn_knie rechts_positive',

    'Zwelling_pols L_positive', 'Zwelling_pols R_positive',
    'Zwelling_pip 2 links hand_positive', 'Zwelling_pip 2 rechts hand_positive',
    'Zwelling_pip 3 links hand_positive', 'Zwelling_pip 3 rechts hand_positive',
    'Zwelling_pip 4 links hand_positive', 'Zwelling_pip 4 rechts hand_positive',
    'Zwelling_pip 5 links hand_positive', 'Zwelling_pip 5 rechts hand_positive',
    'Zwelling_mcp 1 links_positive', 'Zwelling_mcp 1 rechts_positive',
    'Zwelling_mcp 2 links_positive', 'Zwelling_mcp 2 rechts_positive',
    'Zwelling_mcp 3 links_positive', 'Zwelling_mcp 3 rechts_positive',
    'Zwelling_mcp 4 links_positive', 'Zwelling_mcp 4 rechts_positive',
    'Zwelling_mcp 5 links_positive', 'Zwelling_mcp 5 rechts_positive',
    'Zwelling_knie links_positive', 'Zwelling_knie rechts_positive',
    'Zwelling_schouder L_positive', 'Zwelling_schouder R_positive',
    'Zwelling_Elleboog L_positive', 'Zwelling_elleboog R_positive',
    'Zwelling_IP links_positive', 'Zwelling_IP rechts_positive'
]
L_DAS_Joints_44 = L_DAS_Joints_28 + [
    'Zwelling_sternoclaviculair L_positive', 'Zwelling_sternoclaviculair R_positive',
    'Pijn_sternoclaviculair L_positive', 'Pijn_sternoclaviculair R_positive',
    'Zwelling_acromioclaviaculair L_positive', 'Zwelling_acromioclaviaculair R_positive',
    'Pijn_acromioclaviaculair L_positive', 'Pijn_acromioclaviaculair R_positive',
    'Pijn_onderste spronggewricht links_positive', 'Pijn_onderste spronggewricht rechts_positive',
    'Pijn_bovenste spronggewicht links_positive', 'Pijn_bovenste spronggewricht rechts_positive',
    'Zwelling_onderste spronggewricht links_positive', 'Zwelling_onderste spronggewricht rechts_positive',
    'Zwelling_bovenste spronggewicht links_positive', 'Zwelling_bovenste spronggewricht rechts_positive',
    'Pijn_mtp 2 links_positive', 'Pijn_mtp 2 rechts_positive',
    'Pijn_mtp 3 links_positive', 'Pijn_mtp 3 rechts_positive',
    'Pijn_mtp 4 links_positive', 'Pijn_mtp 4 rechts_positive',
    'Pijn_mtp 5 links_positive', 'Pijn_mtp 5 rechts_positive',
    'Zwelling_mtp 2 links_positive', 'Zwelling_mtp 2 rechts_positive',
    'Zwelling_mtp 3 links_positive', 'Zwelling_mtp 3 rechts_positive',
    'Zwelling_mtp 4 links_positive', 'Zwelling_mtp 4 rechts_positive',
    'Zwelling_mtp 5 links_positive', 'Zwelling_mtp 5 rechts_positive'
]

L_DAS_Joints_66 = L_DAS_Joints_44 + [
    'Pijn_dip 2 links_positive',
     'Pijn_dip 2 rechts_positive',
     'Pijn_dip 3 links_positive',
     'Pijn_dip 3 rechts_positive',
     'Pijn_dip 4 links_positive',
     'Pijn_dip 4 rechts_positive',
     'Pijn_dip 5 links_positive',
     'Pijn_dip 5 rechts_positive',
     'Pijn_mtp 1 links_positive',
     'Pijn_mtp 1 rechts_positive',
     'Pijn_tarsometatarsaal L_positive',
     'Pijn_tarsometatarsaal R_positive',
     'Pijn_temporomandibulair L_positive',
     'Pijn_temporomandibulair R_positive',
    
    'Pijn_pip 2 links voet_positive',
     'Pijn_pip 2 rechts voet_positive',
     'Pijn_pip 3 links voet_positive',
     'Pijn_pip 3 rechts voet_positive',
     'Pijn_pip 4 links voet_positive',
     'Pijn_pip 4 rechts voet_positive',
     'Pijn_pip 5 links voet_positive',
     'Pijn_pip 5 rechts voet_positive',
    
    # For HIP Only tender -> that is why TJC = 68; and SJC = 66
    'Pijn_heup links_positive',
    'Pijn_heup rechts_positive',
    
     'Zwelling_dip 2 links_positive',
     'Zwelling_dip 2 rechts_positive',
     'Zwelling_dip 3 links_positive',
     'Zwelling_dip 3 rechts_positive',
     'Zwelling_dip 4 links_positive',
     'Zwelling_dip 4 rechts_positive',
     'Zwelling_dip 5 links_positive',
     'Zwelling_dip 5 rechts_positive',
     'Zwelling_mtp 1 links_positive',
     'Zwelling_mtp 1 rechts_positive',
     'Zwelling_tarsometatarsaal L_positive',
     'Zwelling_tarsometatarsaal R_positive',
     'Zwelling_temporomandibulair L_positive',
     'Zwelling_temporomandibulair R_positive',
    
    'Zwelling_pip 2 rechts voet_positive',
    'Zwelling_pip 3 links voet_positive',
    'Zwelling_pip 3 rechts voet_positive',
    'Zwelling_pip 4 links voet_positive',
    'Zwelling_pip 4 rechts voet_positive',
    'Zwelling_pip 5 links voet_positive',
    'Zwelling_pip 5 rechts voet_positive',

]
